/*
 * Mattermost API Reference
 *
 * There is also a work-in-progress [Postman API reference](https://documenter.getpostman.com/view/4508214/RW8FERUn). 
 *
 * The version of the OpenAPI document: 4.0.0
 * Contact: feedback@mattermost.com
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct FilesLimits {
    #[serde(rename = "total_storage", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub total_storage: Option<Option<i64>>,
}

impl FilesLimits {
    pub fn new() -> FilesLimits {
        FilesLimits {
            total_storage: None,
        }
    }
}


