/*
 * Mattermost API Reference
 *
 * There is also a work-in-progress [Postman API reference](https://documenter.getpostman.com/view/4508214/RW8FERUn). 
 *
 * The version of the OpenAPI document: 4.0.0
 * Contact: feedback@mattermost.com
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct GetSamlMetadataFromIdpRequest {
    /// The URL from which to retrieve the SAML IDP data.
    #[serde(rename = "saml_metadata_url", skip_serializing_if = "Option::is_none")]
    pub saml_metadata_url: Option<String>,
}

impl GetSamlMetadataFromIdpRequest {
    pub fn new() -> GetSamlMetadataFromIdpRequest {
        GetSamlMetadataFromIdpRequest {
            saml_metadata_url: None,
        }
    }
}


