/*
 * Mattermost API Reference
 *
 * There is also a work-in-progress [Postman API reference](https://documenter.getpostman.com/view/4508214/RW8FERUn). 
 *
 * The version of the OpenAPI document: 4.0.0
 * Contact: feedback@mattermost.com
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct InlineObject101 {
    /// The ID of the plugin to install.
    #[serde(rename = "id")]
    pub id: String,
}

impl InlineObject101 {
    pub fn new(id: String) -> InlineObject101 {
        InlineObject101 {
            id,
        }
    }
}


