/*
 * Mattermost API Reference
 *
 * There is also a work-in-progress [Postman API reference](https://documenter.getpostman.com/view/4508214/RW8FERUn). 
 *
 * The version of the OpenAPI document: 4.0.0
 * Contact: feedback@mattermost.com
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct InlineObject19 {
    /// A description of the token usage
    #[serde(rename = "description")]
    pub description: String,
}

impl InlineObject19 {
    pub fn new(description: String) -> InlineObject19 {
        InlineObject19 {
            description,
        }
    }
}


