/*
 * Mattermost API Reference
 *
 * There is also a work-in-progress [Postman API reference](https://documenter.getpostman.com/view/4508214/RW8FERUn). 
 *
 * The version of the OpenAPI document: 4.0.0
 * Contact: feedback@mattermost.com
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct RegisterTermsOfServiceActionRequest {
    /// terms of service ID on which the user is acting on
    #[serde(rename = "serviceTermsId")]
    pub service_terms_id: String,
    /// true or false, indicates whether the user accepted or rejected the terms of service.
    #[serde(rename = "accepted")]
    pub accepted: String,
}

impl RegisterTermsOfServiceActionRequest {
    pub fn new(service_terms_id: String, accepted: String) -> RegisterTermsOfServiceActionRequest {
        RegisterTermsOfServiceActionRequest {
            service_terms_id,
            accepted,
        }
    }
}


