/*
 * Mattermost API Reference
 *
 * There is also a work-in-progress [Postman API reference](https://documenter.getpostman.com/view/4508214/RW8FERUn). 
 *
 * The version of the OpenAPI document: 4.0.0
 * Contact: feedback@mattermost.com
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct SearchUserAccessTokensRequest {
    /// The search term to match against the token id, user id or username.
    #[serde(rename = "term")]
    pub term: String,
}

impl SearchUserAccessTokensRequest {
    pub fn new(term: String) -> SearchUserAccessTokensRequest {
        SearchUserAccessTokensRequest {
            term,
        }
    }
}


