/*
 * Mattermost API Reference
 *
 * There is also a work-in-progress [Postman API reference](https://documenter.getpostman.com/view/4508214/RW8FERUn). 
 *
 * The version of the OpenAPI document: 4.0.0
 * Contact: feedback@mattermost.com
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct TeamsLimits {
    #[serde(rename = "active", skip_serializing_if = "Option::is_none")]
    pub active: Option<i64>,
}

impl TeamsLimits {
    pub fn new() -> TeamsLimits {
        TeamsLimits {
            active: None,
        }
    }
}


